project:
  type: website
  output-dir: docs
  # render:
  #   - "!REMEAD.md"
  #   - "!ignored-dir/"

website:
  title: "Kurisu yuuko's website"
  page-navigation: true
  reader-mode: true
  search: true
  navbar:
    background: primary #背景颜色
    foreground: dark
    search: true
    left:
      - href: index.md
        text: Home
      - href: about.md
        text: about
      - href: CV.md
        text: CV
  sidebar:
    style: "docked" #停靠或者浮动 floating
    type: 
    alignment: center
    search: true
    # contents: auto
    collapse-level: 3
    contents:
      - section: "Kurisu's Blog"
        contents:
          - href: src\weekly\index.qmd
            text: 周记
          - href: src\blog\index.qmd
            text: 博客
      - section: "Project"
        contents:
          - href: src\projectshow\index.qmd
            text: 项目成果展示
          - href: src\proceeding\index.qmd
            text: 长期项目推进
      - section: "Technical"
        contents:
          - href: src\techdoc\index.qmd
            text: 技术博客
          - href: src\paperread\index.qmd
            text: 论文精读
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com
  page-footer: 
    # border:false
    background: light
    left: "Copyright 2021, Kurisu Yukko" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [edit, issue]
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



